# Generated by Django 4.2.10 on 2024-02-14 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nasa_image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'title', 'description', 'image_url', 'date')},
        ),
    ]
